FROM rocker/rstudio:4.1.1

RUN apt-get update -y

RUN apt install -y software-properties-common

RUN apt update -y

RUN sed -i "/^# deb.*universe/ s/^# //" /etc/apt/sources.list

RUN apt install -y alien

RUN apt install -y wget

RUN wget http://www.unafold.org/download/oligoarrayaux-3.8-1.x86_64.rpm

RUN alien -i oligoarrayaux-3.8-1.x86_64.rpm

RUN apt-get install -y libcurl4-gnutls-dev 

RUN apt-get install -y \
    libxml2 \
    libxt6 \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libpcre3-dev \
    libicu-dev \
    libjpeg-dev \
    libpng-dev \
    libxml2-dev \
    libglpk-dev


RUN Rscript -e "install.packages('devtools', repos='http://cran.us.r-project.org')"

RUN Rscript -e "install.packages('rmarkdown', repos='http://cran.us.r-project.org')"

RUN Rscript -e "install.packages('TmCalculator', repos='http://cran.us.r-project.org')"

RUN Rscript -e "install.packages('tidyverse', repos='http://cran.us.r-project.org')"

RUN Rscript -e "install.packages('BiocManager', repos='http://cran.us.r-project.org')"

RUN Rscript -e "BiocManager::install('DECIPHER')"

CMD [ "/init" ]
